service: quick-maths

custom:
  config: ${file(src/config/index.js):asFunction}

  DynamoDBBillingMode:
    production: PAY_PER_REQUEST
    staging: PROVISIONED

  DynamoDBCapacity:
    production: !Ref AWS::NoValue
    staging:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: !GetAtt TableUsers.Arn
  environment:
    NODE_ENV: ${opt:stage}

functions:
  alexa:
    timeout: 6
    handler: src/handler.alexaHandler
    memorySize: 512
    events:
      - alexaSkill: ${env:SKILL_ID}
  googleAction:
    timeout: 10
    handler: src/handler.assistantHandler
    memorySize: 512
    events:
      - http:
          path: googleAction
          method: POST
          private: true # Requires clients to add API keys values in the `x-api-key` header of their request

package:
  excludeDevDependencies: true
  include:
    - src/config/*.json
    - src/languageResources/*.json

  exclude:
    - scripts/**
    - assets/**
    - reports/**
    - speech-assets/**

resources:
  Resources:
    assets:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.config.s3.bucket}
        AccessControl: PublicRead
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - "*"
              AllowedMethods:
                - GET

    TableUsers:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.config.dynamodb.tables.users}
        BillingMode: ${self:custom.DynamoDBBillingMode.${env:NODE_ENV}}
        ProvisionedThroughput: ${self:custom.DynamoDBCapacity.${env:NODE_ENV}}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
